# Generated by Django 5.2.5 on 2025-08-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
    ]
